#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e
mv $HOME/120/fps90 /data/data/com.termux/files/usr/bin/
echo "ONE TIME DONE"
chmod +x /data/data/com.termux/files/usr/bin/fps90
echo "Permission enabled"
cd
# Update and upgrade Termux packages, automatically answering "yes"
pkg update -y && pkg upgrade -y || { echo "Failed to update and upgrade packages"; exit 1; }
# Install additional packages
pkg install -y zip || { echo "Failed to install zip"; exit 1; }
pkg install -y unzip || { echo "Failed to install unzip"; exit 1; }
pkg install -y python || { echo "Failed to install python"; exit 1; }
pkg install -y python-pip || { echo "Failed to install python-pip"; exit 1; }
cd $HOME
